### ISSUE TITLE
[NPC][CLASSIC] Greater Spindleweb

### ISSUE THREAD

**Issue by Grinegore** [starrheld/STARRHELD-3.3.5#15]
Will update 
---

- [x] Wrong position of NPC(S), should be moved.

![wowscrnshot_020117_192645](https://cloud.githubusercontent.com/assets/25371702/22520393/6e3b1b38-e8b4-11e6-84b7-c5ade43b5d75.jpg)

**Comment by starrheld** [comment]
CORE ISSUE / MAPS
WILL TAKE TIME
